In [2]:
import cv2
import numpy as np

### add, sub, mult, div

In [3]:
src = np.full((2,2),100,np.uint8)

print('<original>')
print(src)

print('<add>')
print(cv2.add(src, 3))
print(cv2.add(src, 200))



<original>
[[100 100]
 [100 100]]
<add>
[[103 103]
 [103 103]]
[[255 255]
 [255 255]]


### difference between float&uint8

In [6]:
src1 = np.zeros((200,200))
src2 = np.zeros((200,200), dtype=np.uint8)

src3 = np.zeros((200,200), dtype=np.uint8)
src4 = np.ones((200,200), dtype=np.uint8)

cv2.imshow('src1', src1)
cv2.imshow('src2',src2)
cv2.imshow('src3',src3)
cv2.imshow('src4',src4)

cv2.waitKey()
cv2.destroyAllWindows()

### access to specific pixel

In [8]:
src1[:,100:200] = 1.
src2[:,100:200] = 255

cv2.imshow('src1', src1)
cv2.imshow('src2', src2)

cv2.waitKey()
cv2.destroyAllWindows()